### PR TITLE
Add live GCS testing

### PR DESCRIPTION
**Pull request by simonbohnen**
- Test GoogleCloudStore against live GCS using Workload Identity Federation

### CODE REVIEW

**Comment by simonbohnen** [comment]
@xhochy Do you know why the `ACTIONS_ID_TOKEN_REQUEST_URL` variable is unavailable in the runs despite declaring the `id-token: write` permission? See this run for example

**Comment by xhochy** [comment]
No idea.

**Comment by simonbohnen** [comment]
Given that it [worked on my repository](https://github.com/simonbohnen/minimalkv/actions/runs/3959152275/jobs/6781605689), I'm suspecting that it will work once the changes have been merged into this repository. Would you be willing to try that?

**Comment by xhochy** [comment]
The tests are broken, probably because the codebase is not compatible with SQLAlchemy 2.0. @simonbohnen @janjagusch can you please also look into that?

**Comment by simonbohnen** [comment]
Looking into that 👌🏼

**Comment by xhochy** [comment]
🎉

**Comment by xhochy** [comment]
🎉

**Pull request merged**
