### PR TITLE
Remove quoting due to gcsfs release

### PR DESCRIPTION
**Pull request by simonbohnen**
We can remove the quoting as there is a [new gcsfs release](https://github.com/fsspec/gcsfs/releases/tag/2022.10.0).
I also added a changelog entry.

### CODE REVIEW

**Comment by simonbohnen** [comment]
> The release that includes this change has to set a lower boundary to the 2022.10.0 release of the gcsfs package. If not, it could get installed with older versions.

It also makes sense to include that constraint in the `environment.yml`, right?

**Comment by ivergara** [comment]
> > The release that includes this change has to set a lower boundary to the 2022.10.0 release of the gcsfs package. If not, it could get installed with older versions.
> 
> It also makes sense to include that constraint in the `environment.yml`, right?

Maybe, but not too critical as it usually installs the latest of everything given the constraints given. But adding that wouldn't hurt.

**Review by xhochy — APPROVED** [review]

**Comment by ivergara** [comment]
In my understanding, this constraint won't help the package installed via pypi.

**Comment by xhochy** [comment]
> In my understanding, this constraint won't help the package installed via pypi.

yes, because we don't have an explicit dependency on `gcsfs`. In conda-forge, we should add a matching `run_constrained` though.

**Pull request merged**
